name: flight_booking
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  bloc: ^9.0.0  # State management package for Flutter
  flutter_bloc: ^9.1.0  # Flutter-specific implementation of Bloc

  equatable: ^2.0.7  # Simplifies equality comparisons in Dart models

  dio: ^5.8.0+1  # Powerful HTTP client for API calls
  retrofit: ^4.4.2  # Type-safe HTTP client generator for Dart using Dio

  flutter_spinkit: ^5.2.1  # Collection of loading indicators (spinners)
  flutter_screenutil: ^5.9.3  # Responsive UI design utility for different screen sizes

  intl: ^0.20.2  # Internationalization and localization support (date, number formats, etc.)

  get_it: ^8.0.3  # Service locator for dependency injection

  pretty_dio_logger: ^1.4.0  # Logs Dio network requests in a readable format

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9  # Code generator for Retrofit (used with build_runner)
  freezed: ^3.0.4              # Code generator for Freezed (used with build_runner)
  freezed_annotation: ^3.0.0   # Annotations for Freezed (used with build_runner)
  build_runner: ^2.4.15        # Required for running code generators like Freezed and Retrofit

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
