name: flight_booking
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  # Internationalization and localization support (date, number formats, etc.)
  intl: ^0.19.0

  # State management package for Flutter
  bloc: ^9.0.0
  # Flutter-specific implementation of Bloc
  flutter_bloc: ^9.1.0

  # Simplifies equality comparisons in Dart models
  equatable: ^2.0.7

  # Powerful HTTP client for API calls
  dio: ^5.8.0+1
  # Type-safe HTTP client generator for Dart using Dio
  retrofit: ^4.4.2

  # Code generator for Freezed (used with build_runner)
  freezed: ^3.0.4
  # Annotations for Freezed (used with build_runner)
  freezed_annotation: ^3.0.0

  # Collection of loading indicators (spinners)
  flutter_spinkit: ^5.2.1

  # Responsive UI design utility for different screen sizes
  flutter_screenutil: ^5.9.3

  # Service locator for dependency injection
  get_it: ^8.0.3

  # For Navigation 2.0
  go_router: ^14.8.1
  lottie: ^3.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code generator for Retrofit (used with build_runner)
  retrofit_generator: ^9.1.9
  # Required for running code generators like Freezed and Retrofit
  build_runner: ^2.4.15
  # Logs Dio network requests in a readable format
  pretty_dio_logger: ^1.4.0
  quick_log: ^5.5.3
  # Generate Assets
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/lottie/


  fonts:
    - family: SfUiDisplay
      fonts:
        - asset: assets/fonts/sf-ui-display-black.otf
          weight: 900
        - asset: assets/fonts/sf-ui-display-bold.otf
          weight: 700
        - asset: assets/fonts/sf-ui-display-bold.otf
          weight: 600
        - asset: assets/fonts/sf-ui-display-bold.otf
          weight: 500
        - asset: assets/fonts/sf-ui-display-medium.otf
          weight: 400
        - asset: assets/fonts/sf-ui-display-light.otf
          weight: 300
        - asset: assets/fonts/sf-ui-display-thin.otf
          weight: 100
